---
title: "Introduction to Data Privacy"
---

The headers below cause the table of contents/dropdown on the right to be visible. 
# What is data privacy?

- Somewhat hard to define
- Nissenbaum's concept (shortly and easy)

In this tutorial, I will use the term data protection. Privacy is a larger term, encompassing values, attitudes, and behaviors, while data protection is more technical and closer to actual mechanisms.

# Why is data protection important?

Some personal reflection tasks

As researchers, our obligation to data protection arises from two (not totally distinct) directions: ethics and law. 

# Data Protection in Research Ethics

Trust of participants in research and researchers extend to handling personal data 
- Participants probably do not read consent forms 

Ethical conventions (Helsinki etc.)

Professional obligations (e.g., as Psychologists)

# Data Protection in Law

Many laws around the globe
Most important and always applies in EU: GDPR (short intro)
- applies in the case of personal data

Define controller and processor in terms of usual research business

Legal basis?

